const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const app=fs.readFileSync('dashboard/web/app.js','utf8');
const company=fs.readFileSync('dashboard/web/company-review.js','utf8');
const context=vm.createContext({document:{addEventListener(){}},setInterval(){}});
vm.runInContext(app.slice(0,app.indexOf("$('#modal').addEventListener('close'")),context);
vm.runInContext(company,context);
vm.runInContext(`
state={settings:{universe:'nifty50'},instruments:[],screens:[],jobs:[]};
companyUniverse='nifty50';
companyState={rows:[{company:{isin:'INE000A01001',symbol:'<TEST>',name:'Example',sector:'Industry'},score:null,coverage_pct:0,status:'missing',flags:['No financial evidence'],article_count:0}],reviews:[],llm:{enabled:false,reason:'Set server credentials'}};
globalThis.page=companyReviewView();
companyFilters.minimum=50;
globalThis.filtered=companyTable();
companyFilters.minimum=0;
companyFilters.complete=true;
globalThis.complete=companyTable();
globalThis.bankFields=companyFinancialFields('bank');
globalThis.companyFields=companyFinancialFields('non_financial');
`,context);
assert.match(context.page,/&lt;TEST&gt;/);
assert.doesNotMatch(context.page,/<TEST>/);
assert.match(context.page,/Not connected/);
assert.match(context.page,/No financial evidence/);
assert.match(context.filtered,/No matching companies/);
assert.match(context.complete,/No matching companies/);
assert.match(context.bankFields,/name="net_npa_pct"/);
assert.doesNotMatch(context.bankFields,/name="debt_equity"/);
assert.match(context.companyFields,/name="cash_profit_ratio"/);
assert.match(company,/form.elements.use_llm.checked/);
assert.match(company,/company\/scan/);
assert.match(context.page,/No articles or source links are required from you/);
assert.match(context.page,/Research stock/);
assert.doesNotMatch(context.page,/Add article|Import evidence JSON/);
assert.match(company,/api\('company\/research','POST'/);
console.log('Automatic research controls, missing data, filters, escaping and sector form checks passed.');
