const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('dashboard/web/app.js','utf8');
const context=vm.createContext({document:{addEventListener(){},querySelector(){return {open:true};}}});
vm.runInContext(source.slice(0,source.indexOf("$('#modal').addEventListener('close'")),context);
(async()=>{
  vm.runInContext(`state={settings:{universe:'nifty50'},jobs:[],runs:[{id:'abcdef123456',strategy_id:'scalping',config:{name:'EMA baseline',start:'2025-02-03',end:'2025-02-07',entry_filter:'ema'},metrics:{trade_count:4,return_pct:-.2}}],scalping_schema:{properties:{},required:['start','end']}};globalThis.view=scalpingView();`,context);
  assert.match(context.view,/EMA baseline/);
  assert.match(context.view,/Compare confirmations/);
  assert.match(context.view,/Scalping backtest/);
  // Exercise the real modal renderer, including every configured field.
  const section=source.slice(source.indexOf('const sections=['),source.indexOf("modal('Scalping backtest',`<form"));
  const keys=[...section.matchAll(/'([a-z_]+)'/g)].map(m=>m[1]);
  context.keys=keys;
  vm.runInContext(`for(const key of keys)state.scalping_schema.properties[key]={type:'number',title:key,default:1};
    for(const key of ['name','start','end','direction','entry_filter','first_entry_time','last_entry_time','square_off_time'])state.scalping_schema.properties[key]={type:'string',title:key};
    state.scalping_schema.properties.entry_filter.enum=['candles','ema','ema_vwap'];
    state.scalping_schema.properties.acknowledge_limitations={type:'boolean',title:'Research acknowledgement'};
    modal=(title,body)=>{globalThis.dialog={title,body};};
    api=async()=>({start:'2025-01-01',end:'2025-02-07'});`,context);
  await vm.runInContext('newScalping()',context);
  assert.equal(context.dialog.title,'Scalping backtest');
  assert.match(context.dialog.body,/id="scalping-form"/);
  for(const key of keys)assert.match(context.dialog.body,new RegExp(`name="${key}"`));
  assert.match(context.dialog.body,/EMA \+ VWAP/);
  assert.match(context.dialog.body,/value="2025-01-31"/);
  vm.runInContext(`newScalping=async seed=>{globalThis.seed=seed;};`,context);
  await vm.runInContext("newBacktest({strategy_id:'scalping',name:'Revised'})",context);
  assert.equal(context.seed.name,'Revised');
  assert.match(source,/api\('jobs\/scalping','POST',cfg\)/);
  assert.match(source,/interval_minutes\+'m'/);
  assert.match(source,/scalping:scalpingView/);
  vm.runInContext(`state.scalping_paper_schema={properties:{capital:{type:'number',title:'Allocated capital'},acknowledge_limitations:{type:'boolean',title:'Accept simulated fills'},auto_run:{type:'boolean',title:'Auto start',default:false}},required:['capital']};
    globalThis.paperEmpty=scalpingPaperView();scalpingPaperForm();`,context);
  assert.match(context.paperEmpty,/Create paper portfolio/);
  assert.doesNotMatch(context.paperEmpty,/data-action="scalping-paper-start"/);
  assert.match(context.dialog.body,/name="capital"[^>]*value=""[^>]*required/);
  assert.match(context.dialog.body,/name="acknowledge_limitations"/);
  assert.doesNotMatch(context.dialog.body,/name="auto_run"[^>]*checked/);
  vm.runInContext(`state.scalping_paper={status:'active',start_session:'2025-02-06',config:{capital:200000,auto_run:false},ledger:{positions:{},trades:[{symbol:'A',direction:'long',entry_date:'2025-02-06',entry_time:'09:49:03',exit_date:'2025-02-06',exit_time:'09:50:04',quantity:1,entry:100,exit:99,pnl:-1,reason:'Stop',partial_exit:true}],orders:[]}};
    state.scalping_runner={running:true,status:'running',message:'<script>bad</script>'};globalThis.paperRunning=scalpingPaperView();`,context);
  assert.match(context.paperRunning,/Pause entries/);
  assert.match(context.paperRunning,/Flatten &amp; stop runner|Flatten & stop runner/);
  assert.match(context.paperRunning,/Export full ledger/);
  assert.match(context.paperRunning,/09:49:03/);
  assert.match(context.paperRunning,/partial/);
  assert.doesNotMatch(context.paperRunning,/<script>/);
  console.log('Scalping page, complete settings modal, rerun routing and minute chart labels passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
